# -*- coding: utf-8 -*-
"""AshleyBrooks_DS21_LS_DS_111_Exploratory_Data_Analysis_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CHt3YFRn1U406YROWwYCN7lKHfKb5F1O

#Learning Objectives

# Exploratory Data Analysis

- Objective 01 - submit assignments and save work via GitHub
- Objective 02 - load a CSV dataset from a URL using `pandas.read_csv`
- Objective 03 - load a CSV dataset from a local file using `pandas.read_csv
- Objective 04 - use basic Pandas functions for Exploratory Data Analysis-EDA
- Objective 05 - describe and discriminate between basic data types such as categorical, quantitative, continuous, discrete, ordinal, nominal and identifier

#Explore the University of California - Irvine Adult Dataset

###1) Load a dataset via its URL.

Load the Adult dataset from: 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'

Specify the column headers as:'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country', 'income']
"""

#Code here
import pandas as pd
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')
column_headers= ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marial-status', 'occupation', 'relationship', 'race', 'sex', 'capial-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', names=column_headers)

"""###2) Print the first 5 and the last 5 rows."""

#Code here
df.head()

#Code here
df.tail()

"""###3) Determine the data type of each varaible."""

#Code here
df.info()

"""###4) Determine the dimensions of the dataset."""

#Code here
df.shape

"""###5) Are there any missing values in the dataset?
Check for missing values using .isnull().sum().
"""

#Code here
df.isnull().sum()

"""###6) Use the .describe() function in order to see the summary statistics of the numeric columns.

Are there any values shown that might be a code for missing data?  We'll learn how to change the values in a DataFrame tomorrow.
"""

#Code here
df.describe()

"""Answer question here.

I do not see a code for missing data.

###7) Use the .describe(exclude='number') function to calculate summary statistics for the non-numeric columns
"""

#Code here
df.describe(exclude='number')

"""###8) Calculate the number of observations in each category of the relationship variable."""

#Code here
df['relationship']

"""###9) Select and print the occupation category."""

#Code here
print(df['occupation'])

"""#Load a dataset saved on your personal computer

Go to the website http://users.stat.ufl.edu/~winner/datasets.html and scroll down to **NASCAR Race Results by Driver 1975-2003**

Download and save the .csv file to your personal computer.

###10) Upload the dataset using the following commands.
"""

from google.colab import files
uploaded = files.upload()

#Code here
df=pd.read_csv('nascard.csv')

"""###11) Print the first 10 rows of the dataset"""

#Code here
df.head(10)

"""###12) Answer the following questions for the variables prize, carMake and driver:


*   Is the variable categorical or quantitative?
*   If the variable is categorical, determine if it is ordinal, nominal or an identifier variable.
*   If the vriable is quantitative, determine if it is continuous or discrite.

#Answer here.

**Prize = Quantitative, Discrete**

**carMake = Categorical, Identifier**

**driver = Categorical, Identifier**

#Data Storytelling Project Milestone

Begin looking at Data Storytelling (previously called Build Week) [project info](https://github.com/LambdaSchool/DS-Unit-1-Build) and at projects created by previous Lambda students.

[Projects — Lambda DS1!](https://drive.google.com/file/d/1RJoAqDgawzSHOJPlDQRRlfz-EnIsskpL/view)
"""